server:
  port: 8081
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    routes:
      - id: users
        uri: http://localhost:8000
        predicates:
            - Path=/**
  eureka:
    instance:
      hostname: localhost
    client:
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka