version: "3.8"
services:
  postgrescontainer:
    image: postgres
    container_name: postgrescontainer
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - type: bind
        source: C:\Users\Juan\OneDrive\Documentos\OzymandiasApp\AdditionalApps\Volumes\postgres
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ozymandiasnetwork

  rediscontainer:
    container_name: rediscontainer
    image: redis
    restart: always
    volumes:
      - type: bind
        source: C:\Users\Juan\OneDrive\Documentos\OzymandiasApp\AdditionalApps\Volumes\redis
        target: /data
    ports:
      - "6379:6379"
    networks:
      - ozymandiasnetwork

  mongocontainer:
    container_name: mongocontainer
    image: mongo
    restart: always
    volumes:
      - type: bind
        source: C:\Users\Juan\OneDrive\Documentos\OzymandiasApp\AdditionalApps\Volumes\mongo
        target: /data/db
    ports:
      - "27017:27017"
    networks:
      - ozymandiasnetwork

  jenkinscontainer:
    container_name: jenkinscontainer
    image: jenkins/jenkins:lts
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - type: bind
        source: C:\Users\Juan\OneDrive\Documentos\OzymandiasApp\AdditionalApps\Volumes\jenkins
        target: /var/jenkins_home
    networks:
      - ozymandiasnetwork

  sonarqubecontainer:
    container_name: sonarqubecontainer
    image: sonarqube
    restart: always
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgrescontainer:5432/postgres
      - SONARQUBE_JDBC_USERNAME=postgres
      - SONARQUBE_JDBC_PASSWORD=12345
    ports:
      - "9000:9000"
    volumes:
      - type: bind
        source: C:\Users\Juan\OneDrive\Documentos\OzymandiasApp\AdditionalApps\Volumes\sonarqube
        target: /opt/sonarqube/conf
    networks:
      - ozymandiasnetwork

networks:
  ozymandiasnetwork:
    driver: bridge